[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyBZIZpjrD62jPMTDPQKS5uBJ4Wj0W1tZmA"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;"

[[redirects]]
  from = "https://tecnico.hidrogest.net/*"
  to = "/index_tecnico_v2025-D.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
